/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "basic_gates.v:1.1-12.10" */
module basic_gates(AandB, AorB, notA, notB, AexorB, AexnorB, AnorB, AnandB, A, B);
  /* src = "basic_gates.v:1.97-1.98" */
  input A;
  wire A;
  /* src = "basic_gates.v:1.27-1.32" */
  output AandB;
  wire AandB;
  /* src = "basic_gates.v:1.65-1.72" */
  output AexnorB;
  wire AexnorB;
  /* src = "basic_gates.v:1.56-1.62" */
  output AexorB;
  wire AexorB;
  /* src = "basic_gates.v:1.82-1.88" */
  output AnandB;
  wire AnandB;
  /* src = "basic_gates.v:1.75-1.80" */
  output AnorB;
  wire AnorB;
  /* src = "basic_gates.v:1.35-1.39" */
  output AorB;
  wire AorB;
  /* src = "basic_gates.v:1.101-1.102" */
  input B;
  wire B;
  /* src = "basic_gates.v:1.42-1.46" */
  output notA;
  wire notA;
  /* src = "basic_gates.v:1.49-1.53" */
  output notB;
  wire notB;
  assign AandB = B & A;
  assign AnandB = ~(B & A);
  assign AorB = B | A;
  assign AnorB = ~(B | A);
  assign AexorB = B ^ A;
  assign AexnorB = ~(B ^ A);
  assign notA = ~A;
  assign notB = ~B;
endmodule
