/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "CLA.v:1.1-20.10" */
module cla(a, b, cin, sum, carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "CLA.v:1.24-1.25" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "CLA.v:1.27-1.28" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "CLA.v:1.69-1.74" */
  output carry;
  wire carry;
  /* src = "CLA.v:1.37-1.40" */
  input cin;
  wire cin;
  /* src = "CLA.v:3.12-3.16" */
  /* unused_bits = "0 1 2" */
  wire [3:0] cout;
  /* src = "CLA.v:1.56-1.59" */
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__nand2_1 _09_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _10_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__maj3_1 _11_ (
    .A(cin),
    .B(a[0]),
    .C(b[0]),
    .X(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(a[1]),
    .B(b[1]),
    .C(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _13_ (
    .A1(a[2]),
    .A2(_03_),
    .B1(b[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o21ai_0 _14_ (
    .A1(_01_),
    .A2(_04_),
    .B1(_00_),
    .Y(carry)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(cin),
    .B(_05_),
    .Y(sum[0])
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_02_),
    .B(_06_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(_03_),
    .B(_07_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__xor2_1 _21_ (
    .A(a[3]),
    .B(b[3]),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _22_ (
    .A(_04_),
    .B(_08_),
    .Y(sum[3])
  );
  assign cout[3] = carry;
endmodule
