/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "even_parity_detector.v:1.1-6.10" */
module even_parity(in, out);
  wire _0_;
  /* src = "even_parity_detector.v:2.12-2.14" */
  input [3:0] in;
  wire [3:0] in;
  /* src = "even_parity_detector.v:3.13-3.16" */
  output [4:0] out;
  wire [4:0] out;
  sky130_fd_sc_hd__xnor3_1 _1_ (
    .A(in[3]),
    .B(in[2]),
    .C(in[1]),
    .X(_0_)
  );
  sky130_fd_sc_hd__xnor2_1 _2_ (
    .A(in[0]),
    .B(_0_),
    .Y(out[4])
  );
  assign out[3:0] = in;
endmodule
