/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "b2g_converter.v:1.1-9.10" */
module b2g(binary, gray);
  /* src = "b2g_converter.v:2.13-2.19" */
  input [3:0] binary;
  wire [3:0] binary;
  /* src = "b2g_converter.v:3.13-3.17" */
  output [3:0] gray;
  wire [3:0] gray;
  sky130_fd_sc_hd__xor2_1 _0_ (
    .A(binary[3]),
    .B(binary[2]),
    .X(gray[2])
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(binary[2]),
    .B(binary[1]),
    .X(gray[1])
  );
  sky130_fd_sc_hd__xor2_1 _2_ (
    .A(binary[1]),
    .B(binary[0]),
    .X(gray[0])
  );
  assign gray[3] = binary[3];
endmodule
