/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "FA.v:1.1-15.10" */
module full_adder(a, b, cin, sum, carry);
  /* src = "FA.v:1.25-1.26" */
  input a;
  wire a;
  /* src = "FA.v:1.27-1.28" */
  input b;
  wire b;
  /* src = "FA.v:1.44-1.49" */
  output carry;
  wire carry;
  /* src = "FA.v:1.29-1.32" */
  input cin;
  wire cin;
  /* src = "FA.v:1.40-1.43" */
  output sum;
  wire sum;
  /* src = "FA.v:2.12-2.14" */
  wire w3;
  /* src = "FA.v:2.18-2.20" */
  wire w5;
  sky130_fd_sc_hd__xor3_1 _0_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(sum)
  );
  sky130_fd_sc_hd__maj3_1 _1_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(carry)
  );
  assign w3 = sum;
  assign w5 = carry;
endmodule
