/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* src = "RCA.v:2.1-4.10" */
module Full_adder(in1, in2, cin, s, c);
  /* src = "RCA.v:2.46-2.47" */
  output c;
  wire c;
  /* src = "RCA.v:2.33-2.36" */
  input cin;
  wire cin;
  /* src = "RCA.v:2.25-2.28" */
  input in1;
  wire in1;
  /* src = "RCA.v:2.29-2.32" */
  input in2;
  wire in2;
  /* src = "RCA.v:2.44-2.45" */
  output s;
  wire s;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(cin),
    .B(in1),
    .C(in2),
    .X(c)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(cin),
    .B(in1),
    .C(in2),
    .X(s)
  );
endmodule

/* top =  1  */
/* src = "RCA.v:7.1-18.10" */
module ripple_carry_adder(a, b, cin, sum, carry);
  /* src = "RCA.v:7.38-7.39" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "RCA.v:7.40-7.41" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "RCA.v:7.79-7.84" */
  output carry;
  wire carry;
  /* src = "RCA.v:7.49-7.52" */
  input cin;
  wire cin;
  /* src = "RCA.v:9.11-9.15" */
  wire [3:0] cout;
  /* src = "RCA.v:7.67-7.70" */
  output [3:0] sum;
  wire [3:0] sum;
  /* module_not_derived = 32'd1 */
  /* src = "RCA.v:11.12-11.44" */
  Full_adder g1 (
    .c(cout[0]),
    .cin(cin),
    .in1(a[0]),
    .in2(b[0]),
    .s(sum[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "RCA.v:12.12-12.48" */
  Full_adder g2 (
    .c(cout[1]),
    .cin(cout[0]),
    .in1(a[1]),
    .in2(b[1]),
    .s(sum[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "RCA.v:13.12-13.48" */
  Full_adder g3 (
    .c(cout[2]),
    .cin(cout[1]),
    .in1(a[2]),
    .in2(b[2]),
    .s(sum[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "RCA.v:14.12-14.48" */
  Full_adder g4 (
    .c(carry),
    .cin(cout[2]),
    .in1(a[3]),
    .in2(b[3]),
    .s(sum[3])
  );
  assign cout[3] = carry;
endmodule
