/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_pos_edge.v:1.1-10.10" *)
module dff_sync_reset(d, clk, reset, q);
  wire _0_;
  (* src = "dff_pos_edge.v:1.33-1.36" *)
  input clk;
  wire clk;
  (* src = "dff_pos_edge.v:1.29-1.30" *)
  input d;
  wire d;
  (* src = "dff_pos_edge.v:1.56-1.57" *)
  output q;
  wire q;
  (* src = "dff_pos_edge.v:1.38-1.43" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__nor2b_1 _1_ (
    .A(reset),
    .B_N(d),
    .Y(_0_)
  );
  (* src = "dff_pos_edge.v:3.1-9.5" *)
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(q)
  );
endmodule
