/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_async_reset_sync_reset.v:1.1-16.10" *)
module dff_async_reset_sync_reset(in, clk, async_reset, sync_reset, q);
  (* src = "dff_async_reset_sync_reset.v:8.5-15.8" *)
  wire _0_;
  wire _1_;
  (* src = "dff_async_reset_sync_reset.v:4.12-4.23" *)
  input async_reset;
  wire async_reset;
  (* src = "dff_async_reset_sync_reset.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "dff_async_reset_sync_reset.v:2.12-2.14" *)
  input in;
  wire in;
  (* src = "dff_async_reset_sync_reset.v:6.16-6.17" *)
  output q;
  wire q;
  (* src = "dff_async_reset_sync_reset.v:5.12-5.22" *)
  input sync_reset;
  wire sync_reset;
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(async_reset),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nor2b_1 _3_ (
    .A(sync_reset),
    .B_N(in),
    .Y(_0_)
  );
  (* src = "dff_async_reset_sync_reset.v:8.5-15.8" *)
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(_1_)
  );
endmodule
