/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "priority_encoder_4x2.v:1.1-21.10" */
module encoder(in, en, y);
  wire _0_;
  /* src = "priority_encoder_4x2.v:3.9-3.11" */
  input en;
  wire en;
  /* src = "priority_encoder_4x2.v:2.15-2.17" */
  input [3:0] in;
  wire [3:0] in;
  /* src = "priority_encoder_4x2.v:4.20-4.21" */
  output [1:0] y;
  wire [1:0] y;
  sky130_fd_sc_hd__nor2b_1 _1_ (
    .A(in[2]),
    .B_N(in[1]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__o21a_1 _2_ (
    .A1(in[3]),
    .A2(_0_),
    .B1(en),
    .X(y[0])
  );
  sky130_fd_sc_hd__o21a_1 _3_ (
    .A1(in[2]),
    .A2(in[3]),
    .B1(en),
    .X(y[1])
  );
endmodule
