/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "mux2x1.v:1.1-7.10" */
module mux2x1(in1, in2, sel, out);
  /* src = "mux2x1.v:1.21-1.24" */
  input in1;
  wire in1;
  /* src = "mux2x1.v:1.26-1.29" */
  input in2;
  wire in2;
  /* src = "mux2x1.v:1.45-1.48" */
  output out;
  wire out;
  /* src = "mux2x1.v:1.32-1.35" */
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in1),
    .A1(in2),
    .S(sel),
    .X(out)
  );
endmodule
