/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "g2b_converter.v:1.1-9.10" */
module g2b_converter(gray, binary);
  wire _0_;
  /* src = "g2b_converter.v:3.13-3.19" */
  output [3:0] binary;
  wire [3:0] binary;
  /* src = "g2b_converter.v:2.12-2.16" */
  input [3:0] gray;
  wire [3:0] gray;
  sky130_fd_sc_hd__xnor2_1 _1_ (
    .A(gray[2]),
    .B(gray[3]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(_0_),
    .Y(binary[2])
  );
  sky130_fd_sc_hd__xnor2_1 _3_ (
    .A(gray[1]),
    .B(_0_),
    .Y(binary[1])
  );
  sky130_fd_sc_hd__xnor3_1 _4_ (
    .A(gray[1]),
    .B(gray[0]),
    .C(_0_),
    .X(binary[0])
  );
  assign binary[3] = gray[3];
endmodule
