/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "decoder2x4.v:1.1-6.10" */
module decoder2x4(a, b, F);
  /* src = "decoder2x4.v:1.46-1.47" */
  output [3:0] F;
  wire [3:0] F;
  /* src = "decoder2x4.v:1.25-1.26" */
  input a;
  wire a;
  /* src = "decoder2x4.v:1.29-1.30" */
  input b;
  wire b;
  sky130_fd_sc_hd__nor2_1 _0_ (
    .A(a),
    .B(b),
    .Y(F[0])
  );
  sky130_fd_sc_hd__nor2b_1 _1_ (
    .A(a),
    .B_N(b),
    .Y(F[1])
  );
  sky130_fd_sc_hd__nor2b_1 _2_ (
    .A(b),
    .B_N(a),
    .Y(F[2])
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(a),
    .B(b),
    .X(F[3])
  );
endmodule
