/* Generated by Yosys 0.33 (git sha1 2584903a060) */

/* top =  1  */
/* src = "decimal_bcd.v:1.1-28.10" */
module bcd(in, en, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  /* src = "decimal_bcd.v:3.7-3.9" */
  input en;
  wire en;
  /* src = "decimal_bcd.v:2.12-2.14" */
  input [9:0] in;
  wire [9:0] in;
  /* src = "decimal_bcd.v:4.17-4.18" */
  output [3:0] y;
  wire [3:0] y;
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(en),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(in[6]),
    .B(in[7]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4_1 _23_ (
    .A(in[6]),
    .B(in[7]),
    .C(in[4]),
    .D(in[5]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(in[8]),
    .B(in[9]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor4b_1 _25_ (
    .A(in[1]),
    .B(in[2]),
    .C(in[0]),
    .D_N(in[3]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(_02_),
    .B(_03_),
    .C(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor4_1 _27_ (
    .A(in[1]),
    .B(in[2]),
    .C(in[3]),
    .D(in[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand4b_1 _28_ (
    .A_N(in[8]),
    .B(in[9]),
    .C(_02_),
    .D(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor2b_1 _29_ (
    .A(in[4]),
    .B_N(in[5]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand4_1 _30_ (
    .A(_01_),
    .B(_03_),
    .C(_06_),
    .D(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor4b_1 _31_ (
    .A(in[6]),
    .B(in[4]),
    .C(in[5]),
    .D_N(in[7]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor4b_1 _32_ (
    .A(in[2]),
    .B(in[3]),
    .C(in[0]),
    .D_N(in[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand3_1 _33_ (
    .A(_02_),
    .B(_03_),
    .C(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a31oi_1 _34_ (
    .A1(_03_),
    .A2(_06_),
    .A3(_10_),
    .B1(_05_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a41oi_1 _35_ (
    .A1(_07_),
    .A2(_09_),
    .A3(_12_),
    .A4(_13_),
    .B1(_00_),
    .Y(y[0])
  );
  sky130_fd_sc_hd__nor4b_1 _36_ (
    .A(in[7]),
    .B(in[4]),
    .C(in[5]),
    .D_N(in[6]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o211ai_1 _37_ (
    .A1(_10_),
    .A2(_14_),
    .B1(_03_),
    .C1(_06_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor4b_1 _38_ (
    .A(in[1]),
    .B(in[3]),
    .C(in[0]),
    .D_N(in[2]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a31oi_1 _39_ (
    .A1(_02_),
    .A2(_03_),
    .A3(_16_),
    .B1(_05_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21oi_1 _40_ (
    .A1(_15_),
    .A2(_17_),
    .B1(_00_),
    .Y(y[1])
  );
  sky130_fd_sc_hd__nor2b_1 _41_ (
    .A(in[5]),
    .B_N(in[4]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o2111ai_1 _42_ (
    .A1(_08_),
    .A2(_18_),
    .B1(_01_),
    .C1(_03_),
    .D1(_06_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _43_ (
    .A1(_15_),
    .A2(_19_),
    .B1(_00_),
    .Y(y[2])
  );
  sky130_fd_sc_hd__nand4b_1 _44_ (
    .A_N(in[9]),
    .B(_02_),
    .C(_06_),
    .D(in[8]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(_07_),
    .A2(_20_),
    .B1(_00_),
    .Y(y[3])
  );
endmodule
